/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Bloody Roar II)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80126174u
#define func_80126174 BootEntry  /* alias */
